// frontend/src/app/logs/page.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { userApi } from '@/services/api'

export default function LogsPage() {
  const [logs, setLogs] = useState<string[]>([])
  const [loading, setLoading] = useState(true)
  const [autoRefresh, setAutoRefresh] = useState(false)
  const [error, setError] = useState('')
  const logsEndRef = useRef<HTMLDivElement>(null)
  const eventSourceRef = useRef<EventSource | null>(null)

  const scrollToBottom = () => {
    logsEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  const loadLogs = async () => {
    setLoading(true)
    setError('')
    
    try {
      const response = await userApi.getRecentLogs(100)
      setLogs(response.data)
    } catch (error: any) {
      setError(error.response?.data?.detail || 'Error loading logs')
    } finally {
      setLoading(false)
    }
  }

  const startLogStream = () => {
    if (eventSourceRef.current) {
      eventSourceRef.current.close()
    }

    try {
      eventSourceRef.current = userApi.getLogStream()
      
      eventSourceRef.current.onmessage = (event) => {
        const newLog = event.data
        setLogs(prevLogs => [...prevLogs, newLog])
        if (autoRefresh) {
          setTimeout(scrollToBottom, 100)
        }
      }
      
      eventSourceRef.current.onerror = (error) => {
        console.error('EventSource failed:', error)
        setError('Lost connection to log stream')
        setAutoRefresh(false)
      }
    } catch (error) {
      console.error('Failed to start log stream:', error)
      setError('Failed to start live log stream')
      setAutoRefresh(false)
    }
  }

  const stopLogStream = () => {
    if (eventSourceRef.current) {
      eventSourceRef.current.close()
      eventSourceRef.current = null
    }
  }

  const handleAutoRefreshToggle = () => {
    if (autoRefresh) {
      setAutoRefresh(false)
      stopLogStream()
    } else {
      setAutoRefresh(true)
      startLogStream()
    }
  }

  const clearLogs = () => {
    setLogs([])
  }

  const refreshLogs = () => {
    loadLogs()
  }

  useEffect(() => {
    loadLogs()
    
    return () => {
      stopLogStream()
    }
  }, [])

  useEffect(() => {
    if (autoRefresh && logs.length > 0) {
      scrollToBottom()
    }
  }, [logs, autoRefresh])

  const formatLogLine = (logLine: string, index: number) => {
    // Simple log line formatting - you can enhance this based on your log format
    const timestamp = new Date().toISOString().slice(11, 19)
    const isError = logLine.toLowerCase().includes('error') || logLine.toLowerCase().includes('failed')
    const isWarning = logLine.toLowerCase().includes('warning') || logLine.toLowerCase().includes('warn')
    const isInfo = logLine.toLowerCase().includes('info') || logLine.toLowerCase().includes('success')
    
    let colorClass = 'text-gray-700'
    if (isError) colorClass = 'text-red-600'
    else if (isWarning) colorClass = 'text-yellow-600'
    else if (isInfo) colorClass = 'text-green-600'

    return (
      <div key={index} className={`font-mono text-sm py-1 ${colorClass}`}>
        <span className="text-gray-500 mr-2">[{String(index + 1).padStart(4, '0')}]</span>
        {logLine}
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">System Logs</h1>
          <p className="text-gray-600 mt-1">Real-time application logs and events</p>
        </div>
        
        <div className="flex space-x-3">
          <button
            onClick={clearLogs}
            className="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700"
          >
            Clear
          </button>
          <button
            onClick={refreshLogs}
            disabled={loading}
            className={`bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 ${loading ? 'opacity-50' : ''}`}
          >
            {loading ? 'Loading...' : 'Refresh'}
          </button>
          <button
            onClick={handleAutoRefreshToggle}
            className={`px-4 py-2 rounded-md ${
              autoRefresh
                ? 'bg-red-600 text-white hover:bg-red-700'
                : 'bg-green-600 text-white hover:bg-green-700'
            }`}
          >
            {autoRefresh ? 'Stop Live' : 'Start Live'}
          </button>
        </div>
      </div>

      {/* Status */}
      <div className="flex items-center space-x-4">
        <div className="flex items-center">
          <div className={`w-3 h-3 rounded-full mr-2 ${autoRefresh ? 'bg-green-500' : 'bg-gray-400'}`}></div>
          <span className="text-sm text-gray-600">
            {autoRefresh ? 'Live updates active' : 'Live updates off'}
          </span>
        </div>
        <div className="text-sm text-gray-600">
          {logs.length} log entries
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <div className="bg-red-100 border border-red-200 text-red-700 px-4 py-3 rounded">
          {error}
        </div>
      )}

      {/* Logs Container */}
      <div className="bg-white rounded-lg shadow">
        <div className="px-6 py-4 border-b bg-gray-50">
          <h2 className="text-lg font-semibold text-gray-900">Log Output</h2>
        </div>
        
        <div className="p-4">
          {loading && logs.length === 0 ? (
            <div className="text-center py-8">
              <div className="inline-block animate-spin rounded-full h-6 w-6 border-b-2 border-blue-600"></div>
              <p className="text-gray-600 mt-2">Loading logs...</p>
            </div>
          ) : logs.length === 0 ? (
            <div className="text-center py-8">
              <p className="text-gray-600">No logs available</p>
            </div>
          ) : (
            <div 
              className="bg-gray-900 rounded-lg p-4 max-h-96 overflow-y-auto"
              style={{ fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace' }}
            >
              {logs.map((logLine, index) => (
                <div key={index} className="text-green-400 text-sm py-0.5">
                  <span className="text-gray-500 mr-2">[{String(index + 1).padStart(4, '0')}]</span>
                  {logLine}
                </div>
              ))}
              <div ref={logsEndRef} />
            </div>
          )}
        </div>
      </div>

      {/* Instructions */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <h3 className="text-sm font-medium text-blue-800 mb-2">💡 Tips</h3>
        <ul className="text-sm text-blue-700 space-y-1">
          <li>• Click "Start Live" to see real-time log updates</li>
          <li>• Use "Refresh" to manually reload recent logs</li>
          <li>• "Clear" will remove all displayed logs from view</li>
          <li>• Logs automatically scroll to bottom when live updates are active</li>
        </ul>
      </div>
    </div>
  )
}

// frontend/src/views/Logs.vue
<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex justify-between items-center">
      <div>
        <h1 class="text-3xl font-bold text-gray-900">System Logs</h1>
        <p class="text-gray-600 mt-1">Real-time system activity and debugging information</p>
      </div>
      <div class="flex space-x-3">
        <button
          @click="toggleAutoRefresh"
          :class="autoRefresh ? 'bg-green-600 hover:bg-green-700' : 'bg-gray-600 hover:bg-gray-700'"
          class="text-white px-4 py-2 rounded-md"
        >
          {{ autoRefresh ? '⏸️ Stop Auto-refresh' : '▶️ Start Auto-refresh' }}
        </button>
        <button
          @click="clearLogs"
          class="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700"
        >
          🗑️ Clear
        </button>
        <button
          @click="refreshLogs"
          :disabled="loading"
          class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50"
        >
          {{ loading ? '🔄 Loading...' : '🔄 Refresh' }}
        </button>
      </div>
    </div>

    <!-- Controls -->
    <div class="bg-white rounded-lg shadow p-4">
      <div class="flex flex-wrap gap-4 items-center">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Log Level</label>
          <select
            v-model="selectedLevel"
            @change="filterLogs"
            class="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="all">All Levels</option>
            <option value="DEBUG">Debug</option>
            <option value="INFO">Info</option>
            <option value="WARNING">Warning</option>
            <option value="ERROR">Error</option>
            <option value="CRITICAL">Critical</option>
          </select>
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Filter User</label>
          <input
            v-model="userFilter"
            @input="filterLogs"
            placeholder="Enter user ID"
            class="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Search</label>
          <input
            v-model="searchQuery"
            @input="filterLogs"
            placeholder="Search in logs..."
            class="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
        </div>

        <div class="flex items-end">
          <button
            @click="exportLogs"
            class="bg-purple-600 text-white px-4 py-2 rounded-md hover:bg-purple-700"
          >
            💾 Export
          </button>
        </div>
      </div>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-sm font-medium text-gray-500">Total Logs</h3>
        <p class="text-2xl font-bold text-blue-600 mt-1">{{ totalLogs }}</p>
      </div>
      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-sm font-medium text-gray-500">Errors</h3>
        <p class="text-2xl font-bold text-red-600 mt-1">{{ errorCount }}</p>
      </div>
      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-sm font-medium text-gray-500">Warnings</h3>
        <p class="text-2xl font-bold text-yellow-600 mt-1">{{ warningCount }}</p>
      </div>
      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-sm font-medium text-gray-500">Last Update</h3>
        <p class="text-sm font-medium text-gray-900 mt-1">{{ lastUpdate }}</p>
      </div>
    </div>

    <!-- Log Display -->
    <div class="bg-white rounded-lg shadow">
      <div class="px-6 py-4 border-b border-gray-200">
        <div class="flex justify-between items-center">
          <h2 class="text-lg font-semibold text-gray-900">
            Log Entries ({{ filteredLogs.length }})
          </h2>
          <div class="text-sm text-gray-600">
            {{ autoRefresh ? '🔴 Live' : '⏸️ Paused' }}
          </div>
        </div>
      </div>

      <div 
        ref="logContainer"
        class="h-96 overflow-y-auto bg-gray-900 text-green-400 font-mono text-sm p-4"
        style="font-family: 'Courier New', monospace;"
      >
        <div
          v-for="(log, index) in filteredLogs"
          :key="index"
          :class="getLogLineClass(log)"
          class="py-1 px-2 rounded hover:bg-gray-800 cursor-pointer"
          @click="selectLog(log)"
        >
          <span class="text-gray-500">{{ formatTimestamp(log.timestamp) }}</span>
          <span :class="getLevelClass(log.level)" class="ml-2 font-bold">{{ log.level }}</span>
          <span class="ml-2 text-white">{{ log.message }}</span>
          <span v-if="log.user_id" class="ml-2 text-blue-400">[user:{{ log.user_id }}]</span>
          <span v-if="log.platform" class="ml-1 text-purple-400">[{{ log.platform }}]</span>
        </div>
        
        <div v-if="filteredLogs.length === 0" class="text-center text-gray-500 py-8">
          No logs match your current filters
        </div>
      </div>
    </div>

    <!-- Selected Log Detail -->
    <div v-if="selectedLog" class="bg-white rounded-lg shadow p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Log Detail</h3>
      <div class="bg-gray-50 rounded-md p-4">
        <pre class="text-sm text-gray-800 whitespace-pre-wrap">{{ JSON.stringify(selectedLog, null, 2) }}</pre>
      </div>
    </div>
  </div>
</template>

<script>
import { userApi } from '../services/api'

export default {
  name: 'Logs',
  data() {
    return {
      logs: [],
      filteredLogs: [],
      selectedLog: null,
      loading: false,
      autoRefresh: false,
      refreshInterval: null,
      selectedLevel: 'all',
      userFilter: '',
      searchQuery: '',
      lastUpdate: 'Never'
    }
  },
  
  computed: {
    totalLogs() {
      return this.logs.length
    },
    
    errorCount() {
      return this.logs.filter(log => log.level === 'ERROR' || log.level === 'CRITICAL').length
    },
    
    warningCount() {
      return this.logs.filter(log => log.level === 'WARNING').length
    }
  },
  
  async mounted() {
    await this.refreshLogs()
  },
  
  beforeUnmount() {
    if (this.refreshInterval) {
      clearInterval(this.refreshInterval)
    }
  },
  
  methods: {
    async refreshLogs() {
      this.loading = true
      try {
        const response = await userApi.getRecentLogs(500)
        this.logs = response.data.logs.map(log => ({
          ...log,
          level: this.extractLevel(log.message),
          user_id: this.extractUserId(log.message),
          platform: this.extractPlatform(log.message)
        }))
        
        this.filterLogs()
        this.lastUpdate = new Date().toLocaleTimeString()
        
        // Auto-scroll to bottom
        this.$nextTick(() => {
          this.scrollToBottom()
        })
        
      } catch (error) {
        console.error('Error fetching logs:', error)
      } finally {
        this.loading = false
      }
    },
    
    filterLogs() {
      let filtered = [...this.logs]
      
      // Filter by level
      if (this.selectedLevel !== 'all') {
        filtered = filtered.filter(log => log.level === this.selectedLevel)
      }
      
      // Filter by user
      if (this.userFilter) {
        filtered = filtered.filter(log => 
          log.user_id && log.user_id.toLowerCase().includes(this.userFilter.toLowerCase())
        )
      }
      
      // Search filter
      if (this.searchQuery) {
        const query = this.searchQuery.toLowerCase()
        filtered = filtered.filter(log =>
          log.message.toLowerCase().includes(query)
        )
      }
      
      this.filteredLogs = filtered
    },
    
    toggleAutoRefresh() {
      this.autoRefresh = !this.autoRefresh
      
      if (this.autoRefresh) {
        this.refreshInterval = setInterval(() => {
          this.refreshLogs()
        }, 2000) // Refresh every 2 seconds
      } else if (this.refreshInterval) {
        clearInterval(this.refreshInterval)
        this.refreshInterval = null
      }
    },
    
    clearLogs() {
      this.logs = []
      this.filteredLogs = []
      this.selectedLog = null
    },
    
    selectLog(log) {
      this.selectedLog = log
    },
    
    scrollToBottom() {
      const container = this.$refs.logContainer
      if (container) {
        container.scrollTop = container.scrollHeight
      }
    },
    
    exportLogs() {
      const data = JSON.stringify(this.filteredLogs, null, 2)
      const blob = new Blob([data], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      
      const a = document.createElement('a')
      a.href = url
      a.download = `user-profiler-logs-${new Date().toISOString().split('T')[0]}.json`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    },
    
    formatTimestamp(timestamp) {
      return new Date(timestamp).toLocaleTimeString()
    },
    
    getLevelClass(level) {
      const classes = {
        'DEBUG': 'text-cyan-400',
        'INFO': 'text-green-400', 
        'WARNING': 'text-yellow-400',
        'ERROR': 'text-red-400',
        'CRITICAL': 'text-red-600'
      }
      return classes[level] || 'text-gray-400'
    },
    
    getLogLineClass(log) {
      if (log.level === 'ERROR' || log.level === 'CRITICAL') {
        return 'bg-red-900 bg-opacity-20 border-l-4 border-red-500'
      } else if (log.level === 'WARNING') {
        return 'bg-yellow-900 bg-opacity-20 border-l-4 border-yellow-500'
      }
      return ''
    },
    
    extractLevel(message) {
      const match = message.match(/\|\s*(DEBUG|INFO|WARNING|ERROR|CRITICAL)\s*\|/)
      return match ? match[1] : 'INFO'
    },
    
    extractUserId(message) {
      const match = message.match(/\[user:([^\]]+)\]/)
      return match ? match[1] : null
    },
    
    extractPlatform(message) {
      const match = message.match(/\[([a-zA-Z_]+)\]/)
      return match && !match[1].startsWith('user:') ? match[1] : null
    }
  }
}
</script>
